// lyrics.mjs: timed lyrics in and out.
//   node tools/lyrics.mjs import <file.lrc|.srt|.vtt|.json> [--video=<slug>] [--shift=0.0] [--hold=6]   → videos/<slug>/lyrics.js
//   node tools/lyrics.mjs srt [--video=<slug>] [--out=…]                                                  → out/youtube/captions.srt
//   node tools/lyrics.mjs show [--video=<slug>]                                                          lines with times, bars, sections
// LRC is the easiest source: most lyric sites have it, and "enhanced" LRC (<mm:ss.xx> before each
// word) gives word-by-word karaoke. Plain text has no timing: run tools/align_lyrics.py to time it against the song.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, extname, dirname, relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import vm from 'node:vm';
import { parseArgs, pickVideo, loadVideo, fail } from './lib.mjs';

const ts = s => { const p = s.trim().replace(',', '.').split(':').map(Number); return p.reduce((a, b) => a * 60 + b, 0); };
const r3 = x => Math.round(x * 1000) / 1000;

// → [[start, end, text, words?], ...] sorted by start
export function parseLyrics(src, kind, { hold = 6, shift = 0 } = {}) {
  let lines = [];
  if (kind === 'lrc') {
    let off = 0;
    for (const raw of src.split(/\r?\n/)) {
      const m = raw.match(/^\s*\[offset:\s*([+-]?\d+)\]/i); if (m) { off = +m[1] / 1000; continue; }
      const tags = [...raw.matchAll(/\[(\d+:\d+(?:[.:]\d+)?)\]/g)]; if (!tags.length) continue;
      let body = raw.replace(/\[(\d+:\d+(?:[.:]\d+)?)\]/g, '').trim();
      const words = [...body.matchAll(/<(\d+:\d+(?:[.:]\d+)?)>\s*([^<]*)/g)].map(w => [ts(w[1]), w[2].trim()]).filter(w => w[1]);
      if (words.length) body = words.map(w => w[1]).join(' ');
      for (const t of tags) lines.push({ start: ts(t[1]) - off, text: body, words: words.length && tags.length === 1 ? words.map(([t, w]) => [t - off, w]) : null });
    }
    lines.sort((a, b) => a.start - b.start);
    // LRC has no end times: a line lasts until the next one (an empty line ends the previous), at most `hold` seconds,
    // or 1.6 s past its last word when words are timed
    lines = lines.map((l, i) => {
      const next = lines[i + 1] ? lines[i + 1].start : Infinity;
      const end = Math.min(next, l.words ? l.words[l.words.length - 1][0] + 1.6 : l.start + hold, l.start + hold);
      return { ...l, end };
    }).filter(l => l.text);
  } else if (kind === 'srt' || kind === 'vtt') {
    for (const block of src.replace(/\r/g, '').split(/\n\s*\n/)) {
      const m = block.match(/(\d*:?\d+:\d+[.,]\d+)\s*-->\s*(\d*:?\d+:\d+[.,]\d+)[^\n]*\n([\s\S]*)/); if (!m) continue;
      const text = m[3].replace(/<[^>]+>/g, '').replace(/\{[^}]+\}/g, '').split('\n').map(s => s.trim()).filter(Boolean).join(' ');
      if (text) lines.push({ start: ts(m[1]), end: ts(m[2]), text, words: null });
    }
  } else if (kind === 'json') {
    lines = JSON.parse(src).map(l => Array.isArray(l) ? { start: l[0], end: l[1], text: l[2], words: l[3] || null } : l);
  } else fail(`can't read .${kind} lyrics (use .lrc, .srt, .vtt or .json; for plain text run tools/align_lyrics.py)`);
  return lines.sort((a, b) => a.start - b.start)
    .map(l => [r3(l.start + shift), r3(l.end + shift), l.text, ...(l.words ? [l.words.map(([t, w]) => [r3(t + shift), w])] : [])]);
}

export function writeLyricsJs(file, L, from) {
  const body = L.map(l => '  ' + JSON.stringify(l)).join(',\n');
  writeFileSync(file, `// lyrics.js: [start, end, text, words?] per line, in song seconds${from ? `; generated by tools/lyrics.mjs from ${from}` : ''}.\n` +
    `// Edit times here directly, or re-import. words = [[time, word], ...] drives word-by-word karaoke.\nvar LYRICS = [\n${body}\n];\n`);
}
export function readLyricsJs(file) {
  if (!existsSync(file)) return [];
  const ctx = {}; vm.runInNewContext(readFileSync(file, 'utf8'), ctx); return ctx.LYRICS || [];
}
const srtTime = t => { const ms = Math.max(0, Math.round(t * 1000)), h = Math.floor(ms / 3600000), m = Math.floor(ms / 60000) % 60, s = Math.floor(ms / 1000) % 60; return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')},${String(ms % 1000).padStart(3, '0')}`; };
export const toSrt = L => L.map((l, i) => `${i + 1}\n${srtTime(l[0])} --> ${srtTime(l[1])}\n${l[2]}\n`).join('\n');

// ---------- CLI ----------
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const args = parseArgs(), [cmd, file] = args._;
  const V = loadVideo(pickVideo(args)), dest = join(V.dir, 'lyrics.js');
  if (cmd === 'import') {
    if (!file || !existsSync(file)) fail('usage: node tools/lyrics.mjs import <file.lrc|.srt|.vtt|.json> --video=<slug>');
    const L = parseLyrics(readFileSync(file, 'utf8'), extname(file).slice(1).toLowerCase(), { hold: +(args.hold || 6), shift: +(args.shift || 0) });
    writeLyricsJs(dest, L, relative(V.dir, file).startsWith('..') ? file.split('/').pop() : relative(V.dir, file));
    console.log(`${L.length} lines (${L.filter(l => l[3]).length} with word times) → ${relative(process.cwd(), dest)}`);
  } else if (cmd === 'srt') {
    const L = readLyricsJs(dest); if (!L.length) fail('no lyrics in lyrics.js');
    const out = args.out || join(V.out, 'youtube', 'captions.srt'); mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, toSrt(L)); console.log(`${L.length} captions → ${relative(process.cwd(), out)}`);
  } else if (cmd === 'show') {
    const L = readLyricsJs(dest), beat = 60 / V.bpm, bpb = V.beatsPerBar || 4;
    const pos = t => { const b = (t - (V.offset || 0)) / beat; return `${Math.floor(b / bpb)}.${(Math.floor(b) % bpb + bpb) % bpb + 1}`; };
    let sec = null;
    for (const [a, b, text] of L) {
      const s = V.sections.filter(x => x.start <= a).pop();
      if (s && s !== sec) { sec = s; console.log(`\n## ${s.name} (${s.id}, ${s.start.toFixed(2)} s)`); }
      console.log(`${a.toFixed(2).padStart(7)}–${b.toFixed(2).padEnd(7)} bar ${pos(a).padEnd(6)} ${text}`);
    }
  } else fail('usage: node tools/lyrics.mjs import|srt|show …');
}
